# Generated by Django 3.1.5 on 2021-02-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20210106_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivefile',
            name='_webasset_hints',
            field=models.JSONField(default=dict),
        ),
    ]
