# Generated by Django 2.1.7 on 2019-02-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_auto_20171008_0827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivefile",
            name="size",
            field=models.BigIntegerField(),
        ),
    ]
