# Generated by Django 3.1.7 on 2021-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_archivefile__webasset_hints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivefile",
            name="created_at",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
