# Generated by Django 2.1.7 on 2019-03-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0004_auto_20190222_1624"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentFile",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
            },
            bases=("archive.archivefile",),
        ),
    ]
