# Generated by Django 2.1.7 on 2019-03-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_attachmentfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivefile",
            options={"ordering": ("archived_at",)},
        ),
    ]
