# Generated by Django 2.2.4 on 2019-09-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0019_migrate_tags"),
        ("archive", "0009_archivefile_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivefile",
            name="license",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="media.License",
            ),
        ),
    ]
