# Generated by Django 2.2.13 on 2020-07-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0011_auto_20200711_2055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivefile",
            name="source_id",
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
