# Generated by Django 2.2.4 on 2019-11-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("sets", "0002_auto_20190910_1247")]

    operations = [migrations.RemoveField(model_name="node", name="tags")]
