# Generated by Django 3.2 on 2021-07-10 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0005_auto_20210329_1758"),
        ("sets", "0002_node_display_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="representative_media",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="media.media",
            ),
        ),
    ]
