language: python
sudo: required
dist: xenial
python: "3.7"

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose pipenv

script:
  - cd backend/
  - pipenv install
  - pipenv run python ./manage.py test