dist: xenial
sudo: required

language: python
python: "3.7"

install:
  - sudo apt-get remove -y docker
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

script:
  - mkdir -p dist/incoming dist/archive dist/webassets
  - ln -s env_files/docker.env .env
  - docker-compose run django python manage.py test