dist: xenial
sudo: required

language: python
python: "3.7"

services:
  - docker
  - postgresql
  - redis-server

before_script:
  - sudo -u postgres createuser `whoami` -s

install:
#  - curl -sSL https://get.docker.com/ | sudo sh
#  - sudo pip install docker-compose
  - sudo pip install pipenv

env:
  - DATABASE_URL=postgres://travis:@127.0.0.1:5432/hav
  - WHAV_DATABASE_URL=postgres://travis:@127.0.0.1:5432/whav
  - DOCKER_COMPOSE_VERSION=1.23.2



script:
  - ln -s env_files/local.env .env
  - cd backend/
  - pipenv install --dev
#  - pipenv install --dev
  - pipenv run python ./manage.py test