services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

install:
  - sudo apt-get install -y linux-image-virtual kernel linux-image-extra-virtual
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
