language: python
sudo: required
dist: xenial
python: "3.7"

services:
  - docker
  - postgresql
  - redis-server

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_script:
  - sudo -u postgres createuser `whoami` -s

install:
#  - curl -sSL https://get.docker.com/ | sudo sh
#  - sudo pip install docker-compose
  - sudo pip install pipenv

script:
  - ln -s env_files/local.env .env
  - cd backend/
  - pipenv install --dev
#  - pipenv install --dev
  - pipenv run python ./manage.py test