dist: xenial
sudo: required

language: python
python: "3.7"

install:
  - sudo pip install docker-compose

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

script:
  - pwd
  - mkdir -p dist/incoming dist/archive dist/webassets
  - ln -s env_files/docker.travis.env .env
  - cat .env && whoami && id
  - docker-compose config
  - docker-compose run django ls -lahR /archive
  - ls -lRah dist/
