FROM node:18-bullseye-slim

WORKDIR /code/

# Link up the required build files
COPY ./src/hav/apps/theme/package.json ./src/hav/apps/theme/package-lock.json ./
RUN npm ci

COPY ./src/hav/apps/theme/src/mdx .

CMD node ./server.mjs
