# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0002_auto_20161121_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='/home/sean/src/hav/dist/media', verbose_name='uploaded file'),
        ),
    ]
