# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 12:05
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_auto_20170116_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/sean/src/hav/dist/media'), upload_to='', verbose_name='uploaded file'),
        ),
    ]
