# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import incoming.validators


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0005_fileingestselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='uploadedfilefolder',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='fileingestselection',
            name='source_references',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, validators=[incoming.validators.validate_list_of_lists]),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.DeleteModel(
            name='UploadedFileFolder',
        ),
    ]
