# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/sean/src/hav/dist/examples/'), upload_to='')),
                ('original_filename', models.CharField(max_length=200)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'image'), ('audio', 'audio'), ('video', 'video')], db_index=True, max_length=10)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Example Media',
            },
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hav_examples.Media'),
        ),
    ]
