# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hav_examples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
