# Generated by Django 3.1.7 on 2021-03-05 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("media", "0002_auto_20210106_2044"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modified_media",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
