# Generated by Django 3.1.7 on 2021-03-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0003_auto_20210305_2122"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="short_code",
            field=models.SlugField(blank=True, default=None, null=True, unique=True),
        ),
    ]
