# Generated by Django 3.2.13 on 2022-05-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_initial_data"),
        ("media", "0006_alter_media_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="literature",
            field=models.ManyToManyField(
                blank=True,
                related_name="is_relevant_literature_for",
                to="publications.Publication",
            ),
        ),
    ]
