# Generated by Django 3.2.13 on 2022-05-24 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_archivefile_prohibit_download"),
        ("media", "0006_alter_media_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaToSubtitleTrack",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "kind",
                    models.IntegerField(
                        choices=[
                            (1, "subtitles"),
                            (2, "captions"),
                            (3, "chapters"),
                            (4, "metadata"),
                        ]
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="media.media"
                    ),
                ),
                (
                    "subtitle_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archive.attachmentfile",
                    ),
                ),
            ],
            options={
                "unique_together": {("media", "subtitle_track")},
            },
        ),
        migrations.AddField(
            model_name="media",
            name="subtitle_tracks",
            field=models.ManyToManyField(
                blank=True,
                related_name="is_subtitle_track_for",
                through="media.MediaToSubtitleTrack",
                to="archive.AttachmentFile",
            ),
        ),
    ]
