# Generated by Django 3.2.13 on 2022-05-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0006_subtitlefile"),
        ("media", "0007_auto_20220524_0232"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mediatosubtitletrack",
            old_name="default",
            new_name="is_default_track",
        ),
        migrations.AlterField(
            model_name="media",
            name="subtitle_tracks",
            field=models.ManyToManyField(
                blank=True,
                related_name="is_subtitle_track_for",
                through="media.MediaToSubtitleTrack",
                to="archive.SubtitleFile",
            ),
        ),
        migrations.AlterField(
            model_name="mediatosubtitletrack",
            name="subtitle_track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="archive.subtitlefile"
            ),
        ),
    ]
