# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-19 17:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestQueue',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selection', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('expanded_selection', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ready_for_ingestion', models.BooleanField(default=False)),
                ('ingested', models.DateTimeField(default=None, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sets.Node')),
            ],
        ),
    ]
