# Generated by Django 2.0 on 2018-02-01 17:33
from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ("ingest", "0001_initial"),
    ]
    operations = [
        HStoreExtension(),
    ]
