# Generated by Django 2.0 on 2018-02-01 17:43

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_hstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestqueue',
            name='ingested_items',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
    ]
