# Generated by Django 2.1 on 2018-08-22 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_auto_20180816_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestqueue',
            name='ingestion_queue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
    ]
