# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-06 16:55
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170116_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('heading', wagtail.wagtailcore.blocks.CharBlock(classname='full title', template='cms/blocks/heading.html')), ('paragraph', wagtail.wagtailcore.blocks.TextBlock()), ('richtext', wagtail.wagtailcore.blocks.RichTextBlock()), ('raw', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock((('caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))))), ('other_media', wagtail.wagtailcore.blocks.StructBlock((('caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=True))))), ('carousel', wagtail.wagtailcore.blocks.StreamBlock((('image', wagtail.wagtailcore.blocks.StructBlock((('caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=True))))), ('media', wagtail.wagtailcore.blocks.StructBlock((('caption', wagtail.wagtailcore.blocks.RichTextBlock(required=False)), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock(required=True)))))))))),
        ),
    ]
