# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-09 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('cms', '0005_auto_20170406_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='CmsPage',
        ),
    ]
