# Generated by Django 3.1.7 on 2021-03-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0004_auto_20210307_2000"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivefile",
            name="prohibit_download",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
