# Generated by Django 3.2.13 on 2022-05-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0005_archivefile_prohibit_download"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubtitleFile",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("archive.attachmentfile",),
        ),
    ]
