# Generated by Django 3.2.20 on 2023-07-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archive", "0005_archivefile_prohibit_download"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivefile",
            name="_webasset_hints",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
