# Generated by Django 2.1 on 2018-08-20 12:48

import apps.webassets.models
from django.db import migrations, models
import hav_utils.storages


class Migration(migrations.Migration):

    dependencies = [
        ("webassets", "0002_auto_20180523_0626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webasset",
            name="file",
            field=models.FileField(
                storage=hav_utils.storages.ProtectedFileSystemStorage(
                    base_url="http://127.0.0.1:9000",
                    location="/home/sean/src/hav/dist/webassets",
                ),
                upload_to=apps.webassets.models.upload_to,
            ),
        ),
    ]
