FROM python:3
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get upgrade -y && apt-get install -y libpq-dev gcc && apt-get autoremove && apt-get autoclean
WORKDIR /hav/_build/
COPY Pipfile Pipfile.lock ./
RUN pip install -U pipenv
RUN pipenv install --system



