# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 20:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archive', '0003_auto_20171008_0827'),
        ('sets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('archive_file', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='archive.ArchiveFile')),
            ],
        ),
        migrations.CreateModel(
            name='MediaCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MediaCreatorRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaToCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaCreator')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Media')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.MediaCreatorRole')),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='creators',
            field=models.ManyToManyField(through='media.MediaToCreator', to='media.MediaCreator', verbose_name='creators'),
        ),
        migrations.AddField(
            model_name='media',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.License'),
        ),
        migrations.AddField(
            model_name='media',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sets.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='mediatocreator',
            unique_together=set([('creator', 'role', 'media')]),
        ),
    ]
