# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0003_auto_20171008_0827"),
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="files",
            field=models.ManyToManyField(to="archive.ArchiveFile"),
        ),
    ]
