# Generated by Django 3.1.7 on 2021-03-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_media_short_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="short_code",
            field=models.SlugField(
                blank=True, default=None, max_length=6, null=True, unique=True
            ),
        ),
    ]
