# Generated by Django 3.2.8 on 2021-10-27 04:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20210329_1758'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='media',
            managers=[
                ('preview_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
