# Generated by Django 2.1.2 on 2018-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_media_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
