# Generated by Django 2.1.7 on 2019-02-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20190223_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='original_media_type',
        ),
    ]
