# Generated by Django 2.1.7 on 2019-02-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_media_original_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='_original_media_type',
            new_name='original_media_type',
        ),
    ]
