# Generated by Django 2.1.7 on 2019-03-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0012_auto_20190327_2009_squashed_0013_remove_media_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"ordering": ("created_at",)},
        ),
    ]
