# Generated by Django 2.2 on 2019-04-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0013_auto_20190327_2049"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediacreator",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
