# Generated by Django 2.2.3 on 2019-08-08 21:48

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_mediacreator_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hav_collections.Collection'),
        ),
        migrations.AlterField(
            model_name='media',
            name='creation_date',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.License'),
        ),
        migrations.AlterUniqueTogether(
            name='mediatype',
            unique_together={('type', 'name')},
        ),
    ]
