# Generated by Django 2.2.4 on 2019-08-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20190820_0703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediacreatorrole',
            old_name='role_name',
            new_name='name',
        ),
    ]
