# Generated by Django 2.2.4 on 2019-11-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("media", "0019_migrate_tags")]

    operations = [migrations.RemoveField(model_name="media", name="tags")]
