# Generated by Django 2.2.4 on 2019-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0004_auto_20191107_1115"),
        ("media", "0020_remove_media_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="media", name="tags", field=models.ManyToManyField(to="tags.Tag")
        )
    ]
