# Generated by Django 2.2.8 on 2020-04-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0021_media_tags"),
    ]

    operations = [
        migrations.RenameField(
            "mediacreator",
            "name",
            "last_name",
        ),
    ]
