# Generated by Django 3.1.3 on 2020-11-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0024_auto_20200707_1054"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="logo",
            field=models.ImageField(blank=True, upload_to="license_logos"),
        ),
    ]
