# Generated by Django 2.2.4 on 2019-08-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hav_collections', '0003_collection_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ManagedTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tags.Tag')),
                ('source', models.CharField(db_index=True, editable=False, max_length=20)),
                ('source_ref', models.CharField(db_index=True, editable=False, max_length=20)),
            ],
            options={
                'unique_together': {('source', 'source_ref')},
            },
            bases=('tags.tag',),
        ),
        migrations.CreateModel(
            name='CollectionTag',
            fields=[
                ('tag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tags.Tag')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hav_collections.Collection')),
            ],
            bases=('tags.tag',),
        ),
    ]
