# Generated by Django 2.2.4 on 2019-10-09 09:44

import apps.tags.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("tags", "0002_auto_20191008_1058")]

    operations = [
        migrations.AlterField(
            model_name="managedtag",
            name="source",
            field=apps.tags.fields.TagSourceChoiceField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="managedtag",
            name="source_ref",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
