# Generated by Django 2.2.4 on 2019-11-07 11:15

import apps.tags.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sets", "0003_remove_node_tags"),
        ("hav_collections", "0003_collection_public"),
        ("media", "0020_remove_media_tags"),
        ("tags", "0003_auto_20191009_0944"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    apps.tags.fields.TagSourceChoiceField(db_index=True, max_length=20),
                ),
                ("source_ref", models.CharField(db_index=True, max_length=50)),
            ],
            options={"unique_together": {("source", "source_ref")}},
        ),
        migrations.AlterUniqueTogether(name="managedtag", unique_together=None),
        migrations.RemoveField(model_name="managedtag", name="tag_ptr"),
        migrations.DeleteModel(name="CollectionTag"),
        migrations.DeleteModel(name="ManagedTag"),
        migrations.AddField(
            model_name="tag",
            name="collection",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="hav_collections.Collection",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tags.TagSource",
            ),
        ),
    ]
