# Generated by Django 3.1.3 on 2021-01-06 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hav_collections", "0001_initial"),
        ("sets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="root_node",
            field=models.OneToOneField(
                limit_choices_to={"depth__lte": 3},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sets.node",
            ),
        ),
    ]
