# Generated by Django 3.2.8 on 2021-11-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hav_collections", "0002_collection_root_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="type",
            field=models.IntegerField(
                choices=[(1, "private"), (2, "project"), (3, "special")], default=1
            ),
        ),
    ]
