# Generated by Django 2.0.6 on 2018-07-07 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("administrators", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
