# Generated by Django 2.0.6 on 2018-07-07 17:38

import apps.hav_collections.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sets", "0001_initial"),
        ("hav_collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="root_node",
            field=models.OneToOneField(
                limit_choices_to=apps.hav_collections.models.root_nodes,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sets.Node",
            ),
        ),
    ]
