# Generated by Django 2.1.5 on 2019-02-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hav_collections', '0002_collection_root_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
