# Generated by Django 2.2.15 on 2020-10-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hav_collections", "0003_collection_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="root_node",
            field=models.OneToOneField(
                limit_choices_to={"depth__lte": 3},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sets.Node",
            ),
        ),
    ]
