# Generated by Django 3.1.3 on 2020-11-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sets", "0005_auto_20191122_0926"),
        ("hav_collections", "0003_collection_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="root_node",
            field=models.OneToOneField(
                limit_choices_to={"depth__lte": 3},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sets.node",
            ),
        ),
    ]
