# Generated by Django 3.2.12 on 2022-02-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hav_collections", "0003_collection_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="type",
            field=models.IntegerField(
                choices=[(1, "private"), (2, "projects"), (3, "special")], default=1
            ),
        ),
    ]
